import pandas as pd
df=pd.read_csv("ipl.csv")
print(df)
print(df.head())
print(df.tail())
print(df.describe())
print(df.columns)
print(df.shape)
print(df.info())
print(df["Player"])
print(df["Player"].head())
print(df[["Player","Runs"]])
print(df.loc[0:5,["Player","Runs"]])
print(df.loc[df["Runs"]>500,["Player","Runs"]])
print(df.iloc[0:5,0:2])
print(df["Strike rate"])
print(df.loc[df["Runs"]==df["Runs"].max(),["Player","Runs"]])
print(df.loc[df["Strike rate"]==df["Strike rate"].max(),["Player","Strike rate"]])
print(df.loc[df["Runs"].sort_values(ascending=False).index,["Player","Runs"]])
print(df.loc[df["Runs"]==df["Runs"].max(),["Player","Runs"]])
print(df.loc[df["Strike rate"]==df["Strike rate"].max(),["Player","Strike rate"]])