import pandas as pd
df=pd.read_csv("weather.csv")
print(df)
print(df.head())
print(df.tail())
print(df.describe())
print(df.columns)
print(df.shape)
print(df.info())
print(df["Temperature"])
print(df["Temperature"].mean())
print(df.loc[df["Temperature"].idxmax()])
print(df.loc[df["Temperature"].idxmin()])
print(df[df["Temperature"] > 35])